ROWS = 25
COLS = 50
WINDOW_HEIGHT = ROWS * 20
WINDOW_WIDTH = COLS * 20
RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3
SOLIDER_START_LOCATION = (0,0)
NUMBER_OF_TRAPS = 20
BACKGROUND_COLOR = (0, 128, 0)
SOLIDER_IMAGE = "solider_img.png"
SOLIDER_WIDTH = 40
SOLIDER_HEIGHT = 80

